services:
  postgres:
    # Nom du conteneur qui sera créé
    container_name: cballot-db
    # Image de base utilisée (vous pouvez changer la version en vous référant au Docker Hub : https://hub.docker.com/)
    image: postgres:17.2
    # Variables d'environnement qui seront utilisées pour configurer le conteneur
    environment:
      # Utilisateur super admin ! Attentation !
      - POSTGRES_USER=${POSTGRES_USER}
      # Mot de passe du super admin, super sensible.
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Nom d'une base de données créée au lancement du conteneur
      - POSTGRES_DB=cballot
    # Redirection de port "local:conteneur"
    ports:
      - "5454:5432"
    # Le "docker engine" tente systématiquement de redémarrer le conteneur
    # de plus, le conteneur est démarrer automatiquement au lancement du "doker engine"
    restart: always
    # Création du volume permettant d'ajouter le script de création de la base de données au conteneur Docker
    volumes:
      - ./db/cballot.sql:/docker-entrypoint-initdb.d/cballot.sql
